### ISSUE TITLE
On random memory segfaults

### ISSUE THREAD

**Issue by theHamsta** [nodefunallowed/oclcl-petalisp#1]
Hi there! Thanks for this awesome project!

I just read about the "random" segfaults in the readme and wondered if it might have something to do 
with out-of-bound threads in the kernel. Some OpenCL implementors like Nvidia recommend performing an explicit out-of-bound check in their kernel as, due to hardware constraints, more threads might be started than requested. Here's one of their kernels from their examples.
```cpp
__kernel void sequence_gpu(__global int *d_ptr, int length)
{
    int elemID = get_global_id(0);
    if (elemID < length)
    {
        unsigned int laneid;
        //This command gets the lane ID within the current warp
        asm("mov.u32 %0, %%laneid;" : "=r"(laneid));
        d_ptr[elemID] = laneid;
    }
}
```

Just leaving this here a hint because I don't know whether that is still a problem nowadays. I am working on a CUDA backend for Petalisp and I returned all threads that might be out-of-bounds. Just to be sure.

**Comment by no-defun-allowed** [comment]
Hello! Thanks for your comments, this seems very useful.

I don't know if the segfaults are due to out of bounds errors, but that definitely is something I should look into. A while back, I had broken reductions by iterating one value over the edge of a storage array, and I got bogus values instead of any kind of "error", so I don't think that would be the cause of segfaults.

This is very handy information though; I have only tested on my AMD graphics card, Intel on macOS and on some free driver on Linux that runs OpenCL code on a CPU.

**Comment by theHamsta** [comment]
Marco will remove reductions from the IR. So there will be no need to implement them anymore. 

If you observed the segfaults on GPU execution it's probably not out-of-bound accesses. You observe them rather as defect pixels on the screen. Was just an random observation.

**Comment by no-defun-allowed** [comment]
Indeed reductions will be removed; but the current implementation of reductions should not cause any problems.

The out-of-bound access was all reading, from what I remember.
